name: easy_sidebar

description: A flexible and customizable sidebar for Flutter dashboards

version: 0.1.0-alpha.7+5

repository: https://github.com/Ali-Mossa-Hub/Easy-Sidebar
homepage: https://github.com/Ali-Mossa-Hub/Easy-Sidebar

license: BSD-3-Clause
environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  meta: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
